import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../../globals.css";
import { ConfigProvider } from "antd";
import Sidebar from "../../../components/admin/layout/sidebar";
import Header from "../../../components/admin/layout/header";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={poppins.className}>

        <div>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: "Poppins, sans-serif",
              }
            }}
          >
            <div className="w-full min-h-screen bg-white flex flex-row">
              <Sidebar />
              <div className="flex-1">
                <Header />
                {children}
              </div>
            </div>
          </ConfigProvider>
        </div>

      </body>
    </html>
  );
}
