import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Col, ConfigProvider, Layout, Row } from "antd";

const poppins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Awan Kusuma",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={poppins.className}>
            <head>
               <meta name="facebook-domain-verification" content="acfu0griqrhm1iisey5ofeyaajulh9"></meta>
            </head>
            <body className={poppins.className}>

                <div>
                    <ConfigProvider
                        theme={{
                            token: {
                                fontFamily: "Poppins, sans-serif",
                            }
                        }}
                    >
                        <Row>
                            <Col span={24}>
                                {children}
                            </Col>
                        </Row>

                    </ConfigProvider>
                </div>

            </body>
        </html>
    );
}
